import type { Metadata } from "next";
import JetBrains_Mono from "next/font/local"; // Importar desde next/font/local
import "./globals.css";

// components
import Header from "@/components/ui/Header"

const jetbrainsMono = JetBrains_Mono({
  src: "./fonts/GeistVF.woff", // Asegúrate de que la fuente esté en public/fonts/
  weight: "100 900",
  variable: "--font-jetbrainsMono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jetbrainsMono.variable} antialiased`} // Usa la variable
      ><Header />
        {children}
      </body>
    </html>
  );
}
